name: 'elementary_data_reliability'
version: '0.1.1'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2
profile: 'elementary'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"


models:



vars:
  table_monitors_config: EDC_METABASE_EXPRIMENTS.SCHEMA_CHANGES.TABLE_MONITORS_CONFIG
  columns_monitors_config: EDC_METABASE_EXPRIMENTS.SCHEMA_CHANGES.COLUMN_MONITORS_CONFIG
  days_back: 7
  default_run_hours_back: 24
  minimal_sample_size: 1
  z_score_treshold: 3

  schemas_for_alert_on_schema_changes:
    - elementary_db.jaffle_shop
    - elementary_db.stresstest

  edr_monitors:
    table:
      - schema_changes
      - row_count
      - freshness

    column_any_type:
      - null_count
      - null_percent

    column_string:
      - min_length
      - max_length
      - average_length
      - missing_count
      - missing_percent

    column_numeric:
      - min
      - max
      - zero_count
      - zero_percent
      - average
      - standard_deviation
      - variance