name: 'elementary_data_reliability'
version: '0.1.1'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2
profile: 'elementary'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"


models:

  elementary_observability:
      +materialized: view


vars:
  monitoring_configuration: MONITORING_CONFIGURATION
  tables_config: EDC_METABASE_EXPRIMENTS.SCHEMA_CHANGES.TABLES_CONFIG
  columns_config: EDC_METABASE_EXPRIMENTS.SCHEMA_CHANGES.COLUMNS_CONFIG
  table_to_monitor: snowflake.account_usage.query_history
  timestamp_field: end_time
  column_to_monitor: total_elapsed_time
  days_back: 7
  configured_schemas: ['ELEMENTARY_DB.STRESSTEST', 'ELEMENTARY_DB.TEST']
  monitored_tables: ['ELEMENTARY_DB.STRESSTEST.TEST_TEST3', 'ELEMENTARY_DB.STRESSTEST.TEST_TEST2', 'ELEMENTARY_DB.STRESSTEST.TEST_TESTA']


