name: 'elementary_integration_tests'
version: '1.0.0'
config-version: 2
profile: 'elementary_tests'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"


seeds:

  elementary_integration_tests:
      test_data:
        +schema: data

      expected:
          expected_alerts:
          +column_types:
            alert_sent: boolean